doctor/urls.py
from django.urls import path
from doctor import views

app_name = 'doctor'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.dr_login,name='login'),
]

smile/urls.py
from django.contrib import admin
from django.urls import path, include
from doctor import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path('doctor/',include('doctor.urls')),
    path('logout/',views.dr_logout,name='logout'),
    path('special/',views.special,name='special'),
]

blog/models.py
from django.db import models

# Create your models here.

doctor/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class DrProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional fields
    specialisation = models.CharField(max_length=100,blank=False)
    description = models.TextField()
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return "Dr. "+self.user.first_name+" "+self.user.last_name

doctor/forms.py
from django import forms
from django.contrib.auth.models import User
from doctor.models import DrProfileInfo

class DrForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','first_name','last_name','email','password')

class DrProfileForm(forms.ModelForm):
    class Meta():
        model = DrProfileInfo
        fields = ('specialisation','description','profile_pic')

blog/views.py
from django.shortcuts import render

# Create your views here.

doctor/views.py
from django.shortcuts import render
from doctor.forms import DrForm, DrProfileForm
from django.views import generic
#import for login and loguot functionality
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.

class IndexView(generic.TemplateView):
    template_name = 'index.html'

def register(request):
    registered = False

    if request.method == 'POST':
        dr_form = DrForm(data=request.POST)
        dr_profile_form = DrProfileForm(data=request.POST)

        if dr_form.is_valid() and dr_profile_form.is_valid():
            dr = dr_form.save()
            dr.set_password(dr.password) # Hashing the password
            dr.save()

            profile = dr_profile_form.save(commit=False)
            profile.user = dr

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(dr_form.errors,dr_profile_form.errors)
    else:
        dr_form = DrForm()
        dr_profile_form = DrProfileForm()

    context = {'DrForm':dr_form, 'DrProfileForm':dr_profile_form, 'registered':registered}
    return render(request,'registration.html',context)


def dr_login(request):

    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return response("Account is not active! Cntact your admin.")
        else:
            print("Authentication faised for {}".format(username))
            return HttpResponse("Authentication failed, Please enter correct credentials!")
    else:
        return render(request,'login.html',{})


@login_required
def dr_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You are logged in successfully!")

doctor/templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login Here.</h1>
    <form action="{% url 'doctor:login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username : </label>
      <input type="text" name="username" placeholder="Enter username"><br>
      <label for="password">Password : </label>
      <input type="password" name="password"><br><br>

      <input type="submit" value="Login">
    </form>
  </div>
{% endblock %}

doctor/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank You for Registring!</h1>

    {% else %}
      <h1>Please Register Here!</h1>
      <h3>Fill below form</h3>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ DrForm.as_p }}
        {{ DrProfileForm.as_p }}
        <input type="submit" value="Register">
      </form>
    {% endif %}
    
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Smile Foundation</title>
    <!-- Compiled and minified CSS bootstrap 3.4.1 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class='nav navbar-nav'>
          <li><a class="navbar-brand" href="{% url 'index' %}">Smile Foundation</a></li>
          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'doctor:register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'doctor:login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to Smile Foundation!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
{% endblock %}